#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int main(void)
{
	char *cipher = "OVSAOXQYVAMFKDNTFHWZKKWQLFCHHDMXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWIYVWBZEZWFJCTQGJSYWGGFNWQDKHOAJAVRJWUUZAVQJCBGUXUPKDSNQAVROCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWZSGOLJPOVWFVWZHGFRFUXETKRCZRWBTLPSNTVESWBHUKTZZCSBUKSZEWRDRUHTPDWJVTYQYLVSJUJTOSUFRKLPPJSKVRDJPSBOAYOMCDSHVZTMQGFHUUMOSLVSLSSGMWDOEZWLEZSFROKAEAZZNIZIYUSHUGLBSWMKVRDAPWHVRXWETDZPRGFIYKKSERWBTLPSYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVGNWZPOWZYHWIYSBGJKJTPLWHOKDMEAHPRRWBTLPSYKLQETSZRZABMWKVVYHMCOCFQYGNHAGRBSDMEAHPRRWBTLPSYKLQETSZRZABMWMSNNDMEAHPRCZQDHSFJUJLDGTKVYVWXDSHVZTMLFRKUKFBSWBWTNLQDUZCHJQBSWFSVYKBTDZOYOYPELVOGYZQYWGCASWASABSHTLQWLCABXJWHDSHVZTMTOOYRAHBZLVSFUMVOGTAHYAKXGHVRXEICQQCZKKBZESGCKSSTFUKBXVAZXKWFJGUWWHWGHWTPLWHOKDMEAHPRRWBTLPSLKSPWWHWGHWBSWFSJODTMWOBNTKEPJZSGOLJPDSHVZTMWWHWGHWTPLWHOKQMLZZSGOLJPLVSEKOQWDPSNTSVDOSFYKLQETSZRZABMWZSGOLJPDSHVZTMJWOVYKLQETSKUOKXPJKCEJKWQOWGQUETPLWHOK";
	int length = strlen(cipher);

	char alphabet[26];
	for (int i = 0; i < 26; i++)
	{
		// 'A' is 65 in ascii code
		alphabet[i] = i + 65;
	}

	char table[26][26];
	for (int i = 0; i < 26; i++)
	{
		for (int j = 0; j < 26; j++)
		{
			table[i][j] = alphabet[(i+j)%26];
		}
	}

	char *key = "SOONGSIL";
	int keylength = strlen(key);
	char *plain = calloc(length, sizeof(char));
	int idx = 0;
	for (int i = 0; i < length; i++)
	{
		int row = key[i % keylength] - 65;
		for (int col = 0; col < 26; col++)
		{
			if (table[row][col] == cipher[i])
			{
				plain[idx] = col + 65;
				idx++;
				break;
			}
		}
	}

	for (int i = 0; i < length; i++)
	{
		printf("%c", plain[i]);
	}
	free(plain);
}
